
name: Build and Deploy

on:
  push:
    branches:
      - master

      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_FIREBASE_KEY: ${{ secrets.REACT_APP_FIREBASE_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_DB_URL: ${{ secrets.REACT_APP_FIREBASE_DB_URL }}
          REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID }}
          REACT_APP_SB: ${{ secrets.REACT_APP_SB }}
          REACT_APP_MESGID: ${{ secrets.REACT_APP_MESGID }}
          REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

